version: '3'

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - go mod tidy

  check-all:
    desc: Run all checks
    cmds:
      - task format
      - task lint
      - task test

  format:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linters
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./...
