version: '3'

includes:
  example:
    taskfile: ./example/taskfile.yml
    dir: ./example
  tracker-go:
    taskfile: ./tracker-go/taskfile.yml
    dir: ./tracker-go
  tracker-py:
    taskfile: ./tracker-py/taskfile.yml
    dir: ./tracker-py
  tracker-rs:
    taskfile: ./tracker-rs/taskfile.yml
    dir: ./tracker-rs
  tracker-ts:
    taskfile: ./tracker-ts/taskfile.yml
    dir: ./tracker-ts
  web:
    taskfile: ./web/taskfile.yml
    dir: ./web

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  setup-uv:
    desc: Install uv
    cmds:
      - curl -LsSf https://astral.sh/uv/install.sh | sh

  check-all:
    desc: Run all checks
    cmds:
      - task tracker-py:check-all
      - task tracker-ts:check-all
