version: '3'

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  setup-uv:
    desc: Install uv
    cmds:
      - curl -LsSf https://astral.sh/uv/install.sh | sh

  install-tracker-py:
    desc: Install dependencies
    dir: tracker-py
    cmds:
      - uv pip install -e ".[dev]"

  start-tracker-py-app:
    desc: Start the tracker app
    dir: tracker-py
    cmds:
      - uv run uvicorn tracker.main:app --host 0.0.0.0 --port 8080

  check-all-tracker-py:
    desc: Run all checks
    dir: tracker-py
    cmds:
      - uv run ruff format .
      - uv run ruff check --fix .
      - uv run mypy .
      - PYTHONPATH=. uv run pytest tests/ .
      - cd .. && PYTHONPATH=tracker-py uv run pytest tracker-py/tests/

  check-all-example:
    desc: Run all checks
    dir: example
    cmds:
      - uv run ruff format .
      - uv run ruff check --fix .
      # - uv run mypy .
      # - uv run pytest tests/ .
