version: '3'

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  check-tracker-all:
    desc: Format Python code with uv and ruff
    cmds:
      - task: format-tracker
      - task: mypy-tracker

  format-tracker:
    internal: true
    dir: tracker
    cmds:
      - uv run ruff check --fix .
      - uv run ruff format .

  mypy-tracker:
    internal: true
    dir: tracker
    cmds:
      - uv run mypy .
