version: '3'

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  check-all-tracker:
    desc: Run all checks
    cmds:
      - task format-tracker
      - task mypy-tracker

  format-tracker:
    desc: Format code
    dir: tracker
    cmds:
      - uv run ruff check --fix .
      - uv run ruff format .

  mypy-tracker:
    desc: Run mypy
    dir: tracker
    cmds:
      - uv run mypy .
