version: '3'

includes:
  example:
    taskfile: ./example/taskfile.yml
    dir: ./example
  tracker-go:
    taskfile: ./tracker-go/taskfile.yml
    dir: ./tracker-go
  tracker-py:
    taskfile: ./tracker-py/taskfile.yml
    dir: ./tracker-py
  tracker-rs:
    taskfile: ./tracker-rs/taskfile.yml
    dir: ./tracker-rs
  tracker-ts:
    taskfile: ./tracker-ts/taskfile.yml
    dir: ./tracker-ts
  web:
    taskfile: ./web/taskfile.yml
    dir: ./web

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  up:
    desc: Start the app
    cmds:
      - docker compose up -d

  restart:
    desc: Restart the app
    cmds:
      - docker compose restart

  down:
    desc: Stop the app
    cmds:
      - docker compose down

  watch-log: 
    desc: watch logs 
    cmds: 
      - docker compose logs -f 

  check-all:
    desc: Run all checks
    cmds:
      - task tracker-py:check-all
      - task tracker-ts:check-all
      - task tracker-go:check-all
      - task tracker-rs:check-all
      - task web:check-all
