version: '3'

tasks:
  default:
    desc: Show help
    cmds:
      - task --list

  setup-uv:
    desc: Install uv
    cmds:
      - curl -fsSL https://deno.land/x/uv/install/install.sh | sh

  ##################
  # Core
  ##################
  install-core:
    desc: Install dependencies
    dir: core
    cmds:
      - uv sync --frozen
      - task: setup-env-core

  migrate-dev-core:
    desc: Run migrations
    dir: core
    cmds:
      - uvx prisma migrate dev --name {{.CLI_ARGS}}
    vars:
      NAME: '{{.CLI_ARGS}}'

  migrate-deploy-core:
    desc: Deploy migrations
    dir: core
    cmds:
      - uvx prisma migrate deploy

  migrate-reset-core:
    desc: Reset migrations
    dir: core
    cmds:
      - uvx prisma migrate reset --force


  setup-env-core:
    desc: Setup environment variables for PostgreSQL
    dir: core
    cmds:
      - |
        if [ ! -f .env ]; then
          echo "POSTGRES_URL=postgresql://postgres:password@localhost:5432/eval_track" > .env
          echo "POSTGRES_SESSION_URL=postgresql://postgres:password@localhost:5432/eval_track" >> .env
        fi

  ##################
  # Tracker
  ##################
  install-tracker:
    desc: Install dependencies
    dir: tracker
    cmds:
      - uv sync --frozen

  start-tracker-app:
    desc: Start the tracker app
    dir: tracker
    cmds:
      - uv run uvicorn tracker.main:app --host 0.0.0.0 --port 8080

  check-all-tracker:
    desc: Run all checks
    cmds:
      - task format-tracker
      - task lint-tracker
      - task mypy-tracker

  format-tracker:
    desc: Format code
    dir: tracker
    cmds:
      - uv run ruff format .

  lint-tracker:
    desc: Run linter
    dir: tracker
    cmds:
      - uv run ruff check --fix .

  mypy-tracker:
    desc: Run mypy
    dir: tracker
    cmds:
      - uv run mypy .

  test-tracker:
    desc: Run tests
    dir: tracker
    cmds:
      - uv run pytest tests/ .
