version: "3"

services:
  tracker:
    build:
      context: ../../tracker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../tracker:/app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  tracker:
  app: