version: '3.8'

services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb

  dynamodb:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:2.5.3
    user: root
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - dynamodb-data:/data

volumes:
  dynamodb-data: