name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'
      - name: Install mkdocs
        run: pip install mkdocs mkdocs-material
      - name: Build docs
        run: mkdocs build --strict
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
