name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  python-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tracker-py
    steps:
      - uses: actions/checkout@v4
      - name: Install task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          task setup-uv
          task install
      - name: Run ruff format check
        run: task check-all

  typescript-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tracker-ts
    steps:
      - uses: actions/checkout@v4
      - name: Install task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: task install
      - name: Run all checks
        run: task check-all

  go-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tracker-go
    steps:
      - uses: actions/checkout@v4
      - name: Install task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run check-all
        run: |
          task check-all

  rust-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tracker-rs
    steps:
      - uses: actions/checkout@v4
      - name: Install task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: checkall
        run: |
          task check-all
