name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tracker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Setup uv
        run: |
          task setup-uv

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.uv/cache
          key: ${{ runner.os }}-uv-${{ hashFiles('tracker/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Setup virtual environment and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv venv
          source .venv/bin/activate
          task install-tracker

      - name: Run code quality checks
        run: |
          task check-all-tracker
          if [ $? -ne 0 ]; then
            echo "Code quality checks failed"
            exit 1
          fi

      - name: Run tests with coverage
        run: |
          task test-tracker
          if [ $? -ne 0 ]; then
            echo "Tests failed"
            exit 1
          fi
          task coverage-tracker
          if [ $? -ne 0 ]; then
            echo "Coverage checks failed"
            exit 1
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            tracker/htmlcov
            tracker/.coverage
