name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: eval_track
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./tracker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Setup uv
        run: |
          task setup-uv

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.uv/cache
          key: ${{ runner.os }}-uv-${{ hashFiles('tracker/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Sync dependencies
        run: |
          uv sync --frozen

      - name: Run check-all-tracker
        run: |
          task check-all-tracker

      - name: Run test-tracker
        env:
          POSTGRES_URL: postgresql://postgres:password@localhost:5432/eval_track
          POSTGRES_SESSION_URL: postgresql://postgres:password@localhost:5432/eval_track
        run: |
          task test-tracker
